# Generated by Django 3.1.4 on 2021-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210112_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('Discription', models.TextField(max_length=100, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='media/Avatar/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тайтл',
                'verbose_name_plural': 'Тайтлы',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='media/Avatar/', verbose_name='Изображение'),
        ),
    ]
